version: 2.1

jobs:

  Hello-World:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World'
            echo 'This is the delivery pipeline'

  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Getting the code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  
  Using-Python:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Checking the version
          command: |
            python --version


workflows:
  test-workflow:
    jobs:
      - Hello-World
      - Fetch-Code:
          requires:
            - Hello-World
      - Using-Python:
          requires:
            - Fetch-Code
