version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World'
            echo 'This is the delivery pipeline'

  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Getting the code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  
  Using-Python:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Checking the version
          command: |
            python --version
  
  Now-Complete:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: approval complete
          command: |
            echo 'The work is now complete'

workflows:
  test-workflow:
    jobs:
      - build
      - Fetch-Code:
          requires:
            - build
      - Using-Python:
          requires:
            - Fetch-Code
      - Hold-for-Approval:
          type: approval
          requires:
            - Using-Python
            - Fetch-Code
      - Now-Complete:
          requires:
            - Hold-for-Approval
