version: 2.1


jobs:

  linting-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Build Docker
          command: docker-compose up --build -d
      - run:
          name: Linting
          command: docker exec -i cicd-demo bash -c "flake8"
      - run:
          name: Test
          command: docker exec -i cicd-demo bash -c "pytest"

  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - add_ssh_keys:
          fingerprints:
            - 5c:53:dc:d1:2d:e6:32:9c:e3:b1:8e:d4:82:31:66:29
      - checkout
      - run:
          name: list files
          command: ls -al

      - run:
          name: deploy
          command: >
            ssh -o StrictHostKeyChecking=no $SERVER_HOST "cd odoo_cicd && source deploy_bash/build.sh $CIRCLE_BRANCH $GIT_USERNAME $GIT_PASSWORD"

      - run:
          name: Success
          when: on_success
          command: |
            curl --header "Content-Type: application/json" \
            --request POST
            --data "{\"cards\":[{\"header\":{\"title\":\"${CIRCLE_JOB} successful.\",\"subtitle\":\"${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}\",\"imageUrl\":\"https://png.pngtree.com/svg/20170510/success_404253.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"topLabel\":\"${CIRCLE_TAG}\",\"content\":\"Credits - ${CIRCLE_USERNAME}\"}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DETAILS\",\"onClick\":{\"openLink\":{\"url\":\"${CIRCLE_BUILD_URL}\"}}}}]}]}]}]}" https://chat.googleapis.com/v1/spaces/AAAAs53zmQs/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=5aWvA08AMpKDDaq7mBeRrsF_CF5PIsW4KAQgzfA3EBA%3D

workflows:
  cicd-workflows:
    jobs:
      - linting-test
      - deploy:
          requires:
            - linting-test
          # filters:
          #   branches:
          #     only: master
