version: 2.1
jobs:

  linting-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
          version: 20.10.14
      - run:
          name: Build Docker 
          command: docker-compose up --build -d
      - run:
          name: Linting
          command: docker exec -i cicd-demo bash -c "flake8"
      - run:
          name: Test
          command: docker exec -i cicd-demo bash -c "pytest"

workflows:
  cicd-workflows:
    jobs:
      - linting-test
